### PR TITLE
Added back agent team as codeowners

### PR DESCRIPTION
**Pull request by juliaElastic**
Added back agent team as codeowners too with backport labels.

### CODE REVIEW

**Comment by juliaElastic** [comment]
How do I fix this error?

```
[2022-11-24T07:33:36.538Z] go: error loading go 1.16 module graph: github.com/elastic/elastic-agent-client/v7@v7.0.0-20221102171927-bc376a4e0f9f requires
[2022-11-24T07:33:36.538Z] 	github.com/elastic/elastic-agent@v0.0.0-20220831162706-5f1e54f40d3e: invalid version: unknown revision 5f1e54f40d3e
[2022-11-24T07:33:36.538Z] 
[2022-11-24T07:33:36.538Z] If reproducibility with go 1.16 is not needed:
[2022-11-24T07:33:36.538Z] 	go mod tidy -compat=1.17
[2022-11-24T07:33:36.538Z] For other options, see:
[2022-11-24T07:33:36.538Z] 	https://golang.org/doc/modules/pruning
[2022-11-24T07:33:36.538Z] Makefile:97: recipe for target 'notice' failed
[2022-11-24T07:33:36.538Z] make[1]: *** [notice] Error 1
[2022-11-24T07:33:36.538Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/_server_fleet-server-mbp_PR-2117/src/github.com/elastic/fleet-server'
[2022-11-24T07:33:36.538Z] Makefile:74: recipe for target 'check-ci' failed
[2022-11-24T07:33:36.538Z] make: *** [check-ci] Error 2
```

**Review by cmacknz — APPROVED** [review]

**Comment by juliaElastic** [comment]
Jenkins, test this please

**Comment by michel-laterman** [comment]
@juliaElastic, it looks like the go mod issue are caused by a bad commit with the elastic-agent client: https://github.com/elastic/elastic-agent-client/pull/48
updating the client version should fix it

**Comment by michel-laterman** [comment]
I've created a PR that update dependencies to the latest patch version: https://github.com/elastic/fleet-server/pull/2126

**Pull request merged**
