### PR TITLE
Populate agent.id field in .fleet-agents index

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Populate agent.id field in .fleet-agents index as requested here:
https://github.com/elastic/fleet-server/issues/595

@scunningham The current agent schema/mapping has "version" field along with "id", if we populate only the "agent.id" it will save the version as "" empty string, so I updated the code to capture the "agent.version" too. Also assumed that the version could be updated for the same "agent.id".
Could you check if my assumptions are correct there? Thanks!

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

## Related issues

- Closes https://github.com/elastic/fleet-server/issues/595

## Screenshots
Screen Shot 2021-08-02 at 8 50 46 AM

### CODE REVIEW

**Review by scunningham — APPROVED** [review]
Looks good.

**Review by pzl — APPROVED** [review]
looks good, thank you

**Comment by aleksmaus** [comment]
@blakerouse I picked up your changes from master branch and it looks like the white space trimming was removed around the version string there. I've put it back. Could you review this please? Thanks!

**Review by blakerouse — APPROVED** [review]
Thanks for adding it back.

Overall this change looks good.

**Pull request merged**
