### PR TITLE
Fix docker image build

### PR DESCRIPTION
**Pull request by aleksmaus**
* Put back the build/ directory that was lost during the repo move.
* Adjusted the Dockerfile to fix the image for the config file and changes project structure (main.go) in ./
* Updated RPM spec and systemd file to include fleet-server.yml

### CODE REVIEW

**Review by scunningham — APPROVED** [review]

**Review by ph — APPROVED** [review]
LGTM, sorry for removing this, I think this is OK for dev, but we will need more work to fit into the existing Elastic distribution. 

@michalpristas known a bit about how it works in Beats and it might be able to help.

**Comment by ruflin** [comment]
The way we use the `build` directory in most other projects is that it only contains generated files and can be thrown away at any time. For the files we have here we sometimes use `dev-tools` / `deploy`. No need to align right now but I think long term it will be confusing when jumping between repos and not be consistent.

**Comment by aleksmaus** [comment]
yeah, can move however we need, just let me know when

**Comment by ruflin** [comment]
@ph @aleksmaus Any preference on a name which is not `build` for these files?

**Comment by ph** [comment]
I will mimic beats' I think _dev-tools_ was an appropriate choice.

**Comment by ruflin** [comment]
Lets go with `dev-tools` for now if there are no objections. @aleksmaus Can you follow up?

**Comment by aleksmaus** [comment]
yep, will move to dev-tools

**Pull request merged**
