### PR TITLE
go life with buildkite pipeline

### PR DESCRIPTION
**Pull request by sharbuz**
## What is the problem this PR solves?

The partial migration of the Jenkins pipeline to the Buildkite pipeline. 

## How does this PR solve the problem?

Migrating the "Release - The final step - go life with the Buildkite pipeline

## Checklist

The Buildkite pipeline will be triggered by this PR and we will see the result
If it's just the PR the `DRA snapshot` and `DRA release` steps will be with the `"--dry-run"` option.
After merging dry-run option will be absent.

## Related issues

Related to the issue: https://github.com/elastic/fleet-server/issues/2517

### CODE REVIEW

**Comment by jlind23** [comment]
@jsoriano @michel-laterman @nchaulet worth having you guys taking a look at this PR as it will impact the fleet server CI.

**Comment by jlind23** [comment]
Bump @jsoriano @michel-laterman @nchaulet

**Review by michel-laterman — APPROVED** [review]
I think this looks good,

Will it be followed up with another PR to remove the jenkinsfile entirely?

**Comment by sharbuz** [comment]
> I think this looks good,
> 
> Will it be followed up with another PR to remove the jenkinsfile entirely?

Thank you @michel-laterman,
Yes, I'll create another PR for deleting Jenkins pipelines and jobs. 
Can I add you to the reviewers?

**Comment by sharbuz** [comment]
Let's merge it on Monday 24th of July.
@jlind23 @alexsapran @mrodm

**Pull request merged**
