### PR TITLE
Revert "Default fleet policy removal"

### PR DESCRIPTION
**Pull request by ph**
Reverts elastic/fleet-server#1157

Reverting we will rework it to make it `non-breaking`.

### CODE REVIEW

**Comment by ph** [comment]
test this please

**Comment by ph** [comment]
```
[2022-04-01T13:17:50.735Z]     enrollment_api_key_integration_test.go:113:   []model.EnrollmentApiKey{
[2022-04-01T13:17:50.735Z]           	{
[2022-04-01T13:17:50.735Z]           		ESDocument: model.ESDocument{
[2022-04-01T13:17:50.735Z]         - 			Id:      "c93fmvc2jgjfauojood0",
[2022-04-01T13:17:50.735Z]         + 			Id:      "c93fmvc2jgjfauojooe0",
[2022-04-01T13:17:50.735Z]           			Version: 0,
[2022-04-01T13:17:50.735Z]           			SeqNo:   0,
[2022-04-01T13:17:50.735Z]           		},
[2022-04-01T13:17:50.735Z]           		Active:    true,
[2022-04-01T13:17:50.735Z]           		ApiKey:    "d2JndlFIWUJJUVVxWDVia2NJTV86X0d6ZmljZGNTc1d4R1otbklrZFFRZw==",
[2022-04-01T13:17:50.735Z]         - 		ApiKeyId:  "c93fmvc2jgjfauojoodg",
[2022-04-01T13:17:50.735Z]         + 		ApiKeyId:  "c93fmvc2jgjfauojooeg",
[2022-04-01T13:17:50.735Z]           		CreatedAt: "2022-04-01T13:17:49Z",
[2022-04-01T13:17:50.735Z]           		ExpireAt:  "",
[2022-04-01T13:17:50.735Z]           		... // 3 identical fields
[2022-04-01T13:17:50.735Z]           	},
[2022-04-01T13:17:50.735Z]           	{
[2022-04-01T13:17:50.735Z]           		ESDocument: model.ESDocument{
[2022-04-01T13:17:50.735Z]         - 			Id:      "c93fmvc2jgjfauojooe0",
[2022-04-01T13:17:50.735Z]         + 			Id:      "c93fmvc2jgjfauojood0",
[2022-04-01T13:17:50.735Z]           			Version: 0,
[2022-04-01T13:17:50.735Z]           			SeqNo:   0,
[2022-04-01T13:17:50.735Z]           		},
[2022-04-01T13:17:50.735Z]           		Active:    true,
[2022-04-01T13:17:50.735Z]           		ApiKey:    "d2JndlFIWUJJUVVxWDVia2NJTV86X0d6ZmljZGNTc1d4R1otbklrZFFRZw==",
[2022-04-01T13:17:50.735Z]         - 		ApiKeyId:  "c93fmvc2jgjfauojooeg",
[2022-04-01T13:17:50.735Z]         + 		ApiKeyId:  "c93fmvc2jgjfauojoodg",
[2022-04-01T13:17:50.735Z]           		CreatedAt: "2022-04-01T13:17:49Z",
[2022-04-01T13:17:50.735Z]           		ExpireAt:  "",
[2022-04-01T13:17:50.735Z]           		... // 3 identical fields
[2022-04-01T13:17:50.735Z]           	},
[2022-04-01T13:17:50.735Z]           }
[2022-04-01T13:17:50.735Z]         
[2022-04-01T13:17:50.735Z] --- FAIL: TestSearchEnrollmentAPIKeyByPolicyID (1.10s)
```
The ci was hiding the real reason.. again :(

**Comment by ph** [comment]
```
[2022-04-01T13:17:50.735Z]     enrollment_api_key_integration_test.go:113:   []model.EnrollmentApiKey{
[2022-04-01T13:17:50.735Z]           	{
[2022-04-01T13:17:50.735Z]           		ESDocument: model.ESDocument{
[2022-04-01T13:17:50.735Z]         - 			Id:      "c93fmvc2jgjfauojood0",
[2022-04-01T13:17:50.735Z]         + 			Id:      "c93fmvc2jgjfauojooe0",
[2022-04-01T13:17:50.735Z]           			Version: 0,
[2022-04-01T13:17:50.735Z]           			SeqNo:   0,
[2022-04-01T13:17:50.735Z]           		},
[2022-04-01T13:17:50.735Z]           		Active:    true,
[2022-04-01T13:17:50.735Z]           		ApiKey:    "d2JndlFIWUJJUVVxWDVia2NJTV86X0d6ZmljZGNTc1d4R1otbklrZFFRZw==",
[2022-04-01T13:17:50.735Z]         - 		ApiKeyId:  "c93fmvc2jgjfauojoodg",
[2022-04-01T13:17:50.735Z]         + 		ApiKeyId:  "c93fmvc2jgjfauojooeg",
[2022-04-01T13:17:50.735Z]           		CreatedAt: "2022-04-01T13:17:49Z",
[2022-04-01T13:17:50.735Z]           		ExpireAt:  "",
[2022-04-01T13:17:50.735Z]           		... // 3 identical fields
[2022-04-01T13:17:50.735Z]           	},
[2022-04-01T13:17:50.735Z]           	{
[2022-04-01T13:17:50.735Z]           		ESDocument: model.ESDocument{
[2022-04-01T13:17:50.735Z]         - 			Id:      "c93fmvc2jgjfauojooe0",
[2022-04-01T13:17:50.735Z]         + 			Id:      "c93fmvc2jgjfauojood0",
[2022-04-01T13:17:50.735Z]           			Version: 0,
[2022-04-01T13:17:50.735Z]           			SeqNo:   0,
[2022-04-01T13:17:50.735Z]           		},
[2022-04-01T13:17:50.735Z]           		Active:    true,
[2022-04-01T13:17:50.735Z]           		ApiKey:    "d2JndlFIWUJJUVVxWDVia2NJTV86X0d6ZmljZGNTc1d4R1otbklrZFFRZw==",
[2022-04-01T13:17:50.735Z]         - 		ApiKeyId:  "c93fmvc2jgjfauojooeg",
[2022-04-01T13:17:50.735Z]         + 		ApiKeyId:  "c93fmvc2jgjfauojoodg",
[2022-04-01T13:17:50.735Z]           		CreatedAt: "2022-04-01T13:17:49Z",
[2022-04-01T13:17:50.735Z]           		ExpireAt:  "",
[2022-04-01T13:17:50.735Z]           		... // 3 identical fields
[2022-04-01T13:17:50.735Z]           	},
[2022-04-01T13:17:50.735Z]           }
[2022-04-01T13:17:50.735Z]         
[2022-04-01T13:17:50.735Z] --- FAIL: TestSearchEnrollmentAPIKeyByPolicyID (1.10s)
```
The ci was hiding the real reason.. again :(

**Comment by ph** [comment]
I think the either the query or the expectation are wrong in this integration test, I am not familiar with the logic but this could potentially hide a bug, I am going to retrigger this test and create an issue to investigate it.

**Comment by ph** [comment]
Please ignore lint, we are reverting changes the linter will yield at us.

**Review by narph — APPROVED** [review]
compared with initial PR , LGTM

**Comment by ph** [comment]
@Mergifyio requeue

**Comment by mdelapenya** [comment]
@mergifyio refresh

**Comment by mdelapenya** [comment]
@Mergifyio backport 8.2

**Pull request merged**
