### PR TITLE
Update go-version

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Update go version to 1.16.5

- Relates https://github.com/elastic/beats/issues/26182

### CODE REVIEW

**Review by urso — APPROVED** [review]

**Comment by urso** [comment]
Looks like the go.mod is incomplete?

**Comment by michel-laterman** [comment]
I'm not really sure what's going on, I can recreate the issue locally but the steps that go says to take to resolve the issue (`go mod download github.com/elastic/go-licenser go.elastic.co/go-licence-detector`) do not fix it

**Comment by urso** [comment]
The recent problem was introduced with introducing `go get ...`. When doing go get you update the dependency you get. In that case the `go-licenser` was updated. `go get` is run in the current working directory, which is contains the fleet-server source. This motivates the go tool to update your dependencies unfortunately. This might update `go.sum` and `go.mod` as well. The newer `go-licenser` version also changes the format it seems, resulting in the huge diff on the notice file.

**Pull request merged**
