### PR TITLE
Propagate checkin status to agent record

### PR DESCRIPTION
**Pull request by scunningham**
## What does this PR do?

Writes out the checkin status field to the last_checkin_status field in the agent record.  This is necessary to support UX changes.

## Why is it important?

UX needs it.

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] I have made corresponding change to the default configuration files
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Setup local fleet server and point an agent at it.  You can validate field change using the dev tools in kibana.

## Screenshots

Screen Shot 2021-06-02 at 3 40 57 PM

### CODE REVIEW

**Comment by jen-huang** [comment]
@ph / @urso This seems like a good candidate to backport to 7.13, what do you think?

**Comment by scunningham** [comment]
I wouldn't backport unless we were backporting the new UX as well.  Not sure we are buying ourselves much otherwise.

**Comment by jen-huang** [comment]
@scunningham We already have code in Fleet that looks at `last_checkin_status` from pre-Fleet Server days, not just for new UX, so this seems like a regression with agent status reporting that we didn't catch in testing.

**Review by jfsiii — APPROVED** [review]
🚀 Thanks for getting this in so quickly. I ran this branch locally and, without any Kibana changes, it now shows an `Unhealthy` badge for an agent with `last_checkin_status` of `degraded`.

Screen Shot 2021-06-03 at 9 33 16 AM
Screen Shot 2021-06-03 at 9 33 28 AM

Without these changes, the UI marks the agents as `Healthy`

**Comment by ph** [comment]
@scunningham based on the discussion from @jen-huang and the comment from @jfsiii I would backport this to 7.13.x too. If it's fine with you I will just add the label.

**Pull request merged**
