### PR TITLE
replace policy_throttle with policy_limit

### LINKED ISSUE #3008: change policy throttle to use rate limiter
We should change the policy throttle to use a [rate.Limiter](https://pkg.go.dev/golang.org/x/time/rate#Limiter) to make it able to handle burst traffic faster and make it consistent with our other limiters.
We can replace the implementation with a limiter with a burst 1 size in order to keep the current behaviour.

This was found during scale testing.

### PR DESCRIPTION
**Pull request by michel-laterman**
## What is the problem this PR solves?

policy_throttle mechanism is not consistent with other rate limit controls in fleet-server

## How does this PR solve the problem?

Deprecate the old policy_throttle setting and replace it with policy_limit so that all of our endpoint/operation limits use similar config and mechanisms for rate control. If no limits are specified the throttle value will be used as the limit interval (with burst 1).

## Design Checklist

- [x] I have ensured my design is stateless and will work when multiple fleet-server instances are behind a load balancer.
- ~~I have or intend to scale test my changes, ensuring it will work reliably with 100K+ agents connected.~~ no changes to default config.
- [x] I have included fail safe mechanisms to limit the load on fleet-server: rate limiting, circuit breakers, caching, load shedding, etc.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)

## Related issues

- Closes #3008

### CODE REVIEW

**Comment by nchaulet** [comment]
@michel-laterman I am not sure a rate limit will work as we want here from what I understand the policy monitor and agent checkin work in different goroutine, and here it will only rate limit the `dispatchPending` function that send a message to the  policy channel, but from what I understand that operation should almost be atomic, so it event with a rate limit of one it will dispatch all the policies change almost at the same time no? 

Happy to discuss this IRL if you want to avoid some comment roundtrip.

**Comment by michel-laterman** [comment]
@nchaulet, the `dispatchPending` method used to dispatch the policy to the 1st subscription in the queue. the throttle-timer that I removed would tick to send the next one.
I recently pushed another change to make `dispatchPending` process the entire subscription queue (in a loop), the limiter is now used as part of the loop.

**Comment by michel-laterman** [comment]
buildkite run perf-tests

**Comment by michel-laterman** [comment]
buildkite run perf-tests

**Comment by michel-laterman** [comment]
buildkite run perf-tests

**Review by nchaulet — APPROVED** [review]
🚀  Should we explicitly configure that limit in fleet-controller for serverless?

**Comment by michel-laterman** [comment]
yes, we should try to change our configuration for serverles

**Pull request merged**
