### PR TITLE
Revert "agent-mode loads output from policy"

### PR DESCRIPTION
**Pull request by michel-laterman**
Reverts elastic/fleet-server#3411

Due to ongoing issues with the current 8.14 BC we should revert this change and reimplement once we have better defined what fleet-server should expect as bootstrap configuration (see https://github.com/elastic/fleet-server/issues/3464)

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Review by nchaulet — APPROVED** [review]

**Comment by michel-laterman** [comment]
@kilfoyle @lucabelluccini we're reverting the reload from output changes from main and the 8.14 release due to instability

**Comment by lucabelluccini** [comment]
Thanks @michel-laterman  for the heads up - I'll take care of the Knowledge article. I've already pinged @greicefaustino & @Maxwellk-Gib who were tracking this.

**Comment by kilfoyle** [comment]
>  we're reverting the reload from output changes from main and the 8.14 release due to instability

Thanks @michel-laterman! I don't recall working on any docs for this, so I think there's nothing to undo. Let me know if that doesn't sound right.

**Comment by michel-laterman** [comment]
@kilfoyle https://github.com/elastic/ingest-docs/pull/1034 will need to be reverted

**Pull request merged**
