### PR TITLE
Add extra protection against accessing null fields to 8.5 migration

### PR DESCRIPTION
**Pull request by AndersonQ**
## What is the problem this PR solves?

// Please do not just reference an issue. Explain WHAT the problem this PR solves here.

## How does this PR solve the problem?

// Explain HOW you solved the problem in your code. It is possible that during PR reviews this changes and then this section should be updated.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
+1

Weird that its needed, but hopefully it fixes the issue.

**Comment by cmacknz** [comment]
@AndersonQ we need to forward port this to main, correct?

**Comment by jlind23** [comment]
@cmacknz We do!

**Comment by AndersonQ** [comment]
Yes, we do

**Comment by AndersonQ** [comment]
forwardport PR created https://github.com/elastic/fleet-server/pull/1926

**Pull request merged**
