### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkSettleES**
Fixed spelling of "compatibility"

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
LGTM

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
@MarkSettleES This has conflicts now. Should we get this in for you or you plan to merge it yourself?

**Comment by EricDavisX** [comment]
this looks revsolved as of about a month ago, I'm merging it.

**Pull request merged**
