### PR TITLE
Support buildmode=pie on 64 bit platforms.

### PR DESCRIPTION
**Pull request by scunningham**
## What does this PR do?

- Enables ASLR build on 64-bit machines.
- Remove 32bit builds.  Fleet Server should not execute on 32bit machine for security reasons.  In particular, ASLR is not effective on 32bit machines.

## Why is it important?

[ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) is an important security mitigation.

## Checklist

- [x ] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## How to test this PR locally

Run make release.
Run tool on corresponding platform to validate ASLR build, eg:

```
osx$ otool -hv ./build/binaries/fleet-server-8.0.0-darwin-x86_64/fleet-server
./build/binaries/fleet-server-8.0.0-darwin-x86_64/fleet-server:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00     EXECUTE    18       2448   NOUNDEFS DYLDLINK TWOLEVEL PIE
```

## Related issues

-Closes https://github.com/elastic/fleet-server/issues/132

### CODE REVIEW

**Review by aleksmaus — APPROVED** [review]

**Review by ruflin — APPROVED** [review]
LGTM

I'm also good with dropping 32bit support for Windows as I don't think fleet-server should run there. @mostlyjason @ph For your awareness, this might need to feed into "supported platforms" somewhere.

**Comment by blakerouse** [comment]
This is going to cause an issue with Elastic Agent. At the moment Elastic Agent expects that all the architectures that it works on all so work on Fleet Server.

Code needs to be added to Elastic Agent to handle this case, where Fleet Server will not be available on a 32bit system.

**Comment by scunningham** [comment]
I've remove the commit that drops 32bit support until the corresponding work can be done in the Agent.

**Comment by mostlyjason** [comment]
Can we document this int he Fleet Server README? Could also be something to add to the package spec @sorantis

**Pull request merged**
