### PR TITLE
Switch to PAT generated token

### PR DESCRIPTION
**Pull request by ev1yehor**
## What is the problem this PR solves?
Switch to PAT generated GH token
// Please do not just reference an issue. Explain WHAT the problem this PR solves here.

## How does this PR solve the problem?

// Explain HOW you solved the problem in your code. It is possible that during PR reviews this changes and then this section should be updated.

## Design Checklist

- [ ] I have ensured my design is stateless and will work when multiple fleet-server instances are behind a load balancer.
- [ ] I have or intend to scale test my changes, ensuring it will work reliably with 100K+ agents connected.
- [ ] I have included fail safe mechanisms to limit the load on fleet-server: rate limiting, circuit breakers, caching, load shedding, etc.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)

## Related issues

- https://github.com/elastic/ingest-dev/issues/3495

### CODE REVIEW

**Comment by jlind23** [comment]
@ev1yehor do we have to keep both of your PR for the PAT switch?
This one and https://github.com/elastic/fleet-server/pull/3672 ?

**Comment by ev1yehor** [comment]
@jlind23 I closed another one. I did it in new branch because I can't test this changes from fork.
Actually once pipeline fleet-server and [fleet-server-package-mbp](https://buildkite.com/elastic/fleet-server-package-mbp) will be green, I will request review.

**Comment by ev1yehor** [comment]
https://buildkite.com/elastic/fleet-server-package-mbp/builds/1013

New PAT generated token used in this pipeline.

**Review by jlind23 — APPROVED** [review]
Approving on the control plane team's behalf, @alexsapran will take a look at give his review from the eng prod team side.

**Review by alexsapran — APPROVED** [review]

**Pull request merged**
