### PR TITLE
chore: use pinned versions

### PR DESCRIPTION
**Pull request by v1v**
## What is the problem this PR solves?

Use pinned version. Otherwise, if breaking changes in the upstream, it will affect the whole project.

It was reverted accidentally, see https://github.com/elastic/fleet-server/pull/3154#discussion_r1425496027

## Design Checklist

- [ ] I have ensured my design is stateless and will work when multiple fleet-server instances are behind a load balancer.
- [ ] I have or intend to scale test my changes, ensuring it will work reliably with 100K+ agents connected.
- [ ] I have included fail safe mechanisms to limit the load on fleet-server: rate limiting, circuit breakers, caching, load shedding, etc.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)

### CODE REVIEW

**Review by juliaElastic — APPROVED** [review]

**Comment by juliaElastic** [comment]
it seems the build still doesn't work with the pinned version, looks like a missing image?
```
Error response from daemon: manifest for docker.elastic.co/cloud-release/elastic-agent-cloud:8.13.0-jqmw70gd-SNAPSHOT not found: manifest unknown: manifest unknown
```

**Comment by v1v** [comment]
> it seems the build still doesn't work with the pinned version, looks like a missing image?

That's something the Release team might be able to answer :/

**Pull request merged**
