### PR TITLE
Cleanup cmd/fleet/main.go

### LINKED ISSUE #1885: Cleanup fleet/cmd
The main command file is 1k lines.

This is difficult to test or even understand what is going on.
We should clean up the main package to move setup logic and allow for further restructuring.

### PR DESCRIPTION
**Pull request by michel-laterman**
## What is the problem this PR solves?

Separate fleet-server startup from setup.
Reduce duplicate code.

## How does this PR solve the problem?

Remove server setup from cmd/fleet into a new package `pkg/server` that has `NewFleet` and `NewAgent` to setup a standalone fleet-server or fleet-server that runs under the agent.
Remove `cache.Config` and replace with `config.Cache`, move config related methods to the config package.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #1885

### CODE REVIEW

**Review by narph — COMMENTED** [review]
@michel-laterman, the changes look good to me but would help if @blakerouse can have a look

**Review by scunningham — APPROVED** [review]
Looks good.  Easier to understand.

**Review by blakerouse — APPROVED** [review]
Looks mostly mechanical +1

**Comment by michel-laterman** [comment]
I'm going to hold off merging this until https://github.com/elastic/fleet-server/pull/1904 is merged so the backport is simpler

**Pull request merged**
