### PR TITLE
Add more span for APM tracking

### PR DESCRIPTION
**Pull request by michel-laterman**
## What is the problem this PR solves?

HTTP transactions in the APM view don't details into what fleet-server is doing for a given request.
For example here's the view of a successful enrollment request during a scale test:

Screenshot 2023-08-28 at 7 25 38 PM

## How does this PR solve the problem?

Add more detailed spans for APM tracking of how the fleet-server processes each endpoint. Add additonal spans to caputre extra calls made when authenticating an api key for an agent (as fleet-server queries elasticsearch in these cases). Attempt to give each http request a span that validates request body, one or more that does work, and one that writes the response. Additional spans try to track all interactions with elasticsearch and link requests from http transactions to the bulker. Add transactions for monitoring and coordinator requests

## How to test this PR locally

Deploy with `services.fleet.version: 84715134a7fc`

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)

## Screenshots

An enroll transaction
Screenshot 2023-09-01 at 2 34 26 PM
Clicking `span links` on the transaction shows the bulker requests:
Screenshot 2023-09-01 at 2 34 40 PM
Clicking a link (in this case for search), brings us to the search transaction:
Screenshot 2023-09-01 at 2 45 59 PM
Viewing links on the search transaction shows all HTTP transactions that have submitted a search request to the queue when the queue is flushed:
Screenshot 2023-09-01 at 2 46 23 PM
An ack transaction
Screenshot 2023-09-01 at 2 48 45 PM
A Checkin transaction:
Screenshot 2023-09-01 at 2 49 15 PM
A view of all bulker transactions:
Screenshot 2023-09-01 at 2 49 33 PM
A view of the new `monitor` transactions:
Screenshot 2023-09-01 at 2 52 37 PM

### CODE REVIEW

**Comment by jlind23** [comment]
@michel-laterman would it make sense to use this PR in order to fix: https://github.com/elastic/fleet-controller/issues/128 ?

**Comment by michel-laterman** [comment]
Currently the https transactions don't show bulker transactions, my pr is just manually injecting spans around most of the transactions that get triggered by an http request.

I can see if there's a more elegant way to link them

**Comment by jlind23** [comment]
@michel-laterman would indeed be great to tackle both at the same time.

**Comment by michel-laterman** [comment]
Here's some current examples of what the traces look like at the moment:
enroll
Screenshot 2023-08-30 at 3 03 49 PM
acks
Screenshot 2023-08-30 at 3 04 39 PM
checkin
Screenshot 2023-08-30 at 3 05 14 PM

One of the strange parts is that (currently) only enroll links to the proxy requests, but the other endpoints do not.
We can also see that an ack request spends most of it's time validating the agent to the api key (i believe this is mostly spent on the agent query to es that I did not add a span to).

I'll try to add spans and see if the bulker requests can be linked

**Comment by jlind23** [comment]
Thanks @michel-laterman for the progress here, the bulker/ES traces will indeed be really helpful.

**Comment by michel-laterman** [comment]
More in-progress screenshots from the last pr that builds https://github.com/elastic/fleet-server/pull/2929/commits/d18feae5afd80152f91a7e684c7f6031d28ff312
enroll
Screenshot 2023-08-31 at 4 28 27 PM
acks
Screenshot 2023-08-31 at 4 28 07 PM
checkin
Screenshot 2023-08-31 at 4 29 29 PM
the linked spans:
Screenshot 2023-08-31 at 4 30 03 PM
and a view of the bulker flushing a queue (from a linked span)
Screenshot 2023-08-31 at 4 31 15 PM

in the subsequent failing commits i've cleaned up the code and make the span/trace naming more consistent (and tried to instrument the monitors as well). It looks like the integration tests are failing, i'l try to fix them and get another set of examples.

However, by itself this does not link the fleet-server (service) to an elasticsearch service, i'm not too sure how to do that @joshdover, do you know? or should I ask around on an apm channel?

**Comment by michel-laterman** [comment]
I'm mostly happy with the state of the pr. 
acks
Screenshot 2023-09-01 at 9 29 58 AM
enroll
Screenshot 2023-09-01 at 9 29 31 AM
checkin
Screenshot 2023-09-01 at 9 30 35 AM
view of the new monitor transactions
Screenshot 2023-09-01 at 9 32 36 AM
an example of a monitor trace
Screenshot 2023-09-01 at 9 32 56 AM
bulker transactions
Screenshot 2023-09-01 at 9 32 20 AM
a queue flush
Screenshot 2023-09-01 at 9 33 29 AM
ensuring leadership
Screenshot 2023-09-01 at 9 33 51 AM

The `action` spans are when something calls a bulker operation (for example `bulker.Read`), the bulker takes the action dispatches it to a queue then collects and returns the response after the queue is flushed.
I think the links right now between action spans and the flushQueue transactions don't work as expected as they don't link to eachother

**Comment by michel-laterman** [comment]
I have no idea why the integration tests are failing, they have passed for me locally

**Review by juliaElastic — APPROVED** [review]
LGTM

**Comment by juliaElastic** [comment]
> I have no idea why the integration tests are failing, they have passed for me locally

The integration tests fail here, is it related to your changes?

```
=== RUN   TestServerInstrumentation
--
  | fleet_integration_test.go:494: Tracing server received request to: /
  | fleet_integration_test.go:494: Tracing server received request to: /config/v1/agents
  | fleet_integration_test.go:494: Tracing server received request to: /intake/v2/events
  | fleet_integration_test.go:494: Tracing server received request to: /intake/v2/events
  | fleet_integration_test.go:570: APM Tracer connected to APM Server, bug in the tracing code
  | FAIL: TestServerInstrumentation (1.16s)
```

**Comment by michel-laterman** [comment]
I think it's a flakey test

**Pull request merged**
