### PR TITLE
Add initial automation rules based on the rules from the beats

### PR DESCRIPTION
**Pull request by ph**
repository.

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
LGTM. I think we will need to adjust some of these later on but lets get it in now.

**Comment by ph** [comment]
@mdelapenya Does something need to be enabled on that repository?

**Comment by mdelapenya** [comment]
I'd say that all these files will prepare the metadata for the repository: codeowners, GH templates and bots.

As always, it depends on team's needs 😊

**Review by mdelapenya — APPROVED** [review]

**Comment by ph** [comment]
@mdelapenya thanks, for the bots do we need to enable it somewhere?

**Comment by mdelapenya** [comment]
> @mdelapenya thanks, for the bots do we need to enable it somewhere?

Nope, the bots are enabled across Elastic repos

**Pull request merged**
